var namespace_padamose =
[
    [ "AbstractValueStack", "d2/d67/class_padamose_1_1_abstract_value_stack.html", "d2/d67/class_padamose_1_1_abstract_value_stack" ],
    [ "AbstractVersionedBranchClient", "d6/d41/class_padamose_1_1_abstract_versioned_branch_client.html", "d6/d41/class_padamose_1_1_abstract_versioned_branch_client" ],
    [ "AbstractVersionedSet", "dd/dd3/class_padamose_1_1_abstract_versioned_set.html", "dd/dd3/class_padamose_1_1_abstract_versioned_set" ],
    [ "InvalidMapNameException", "d3/d9c/class_padamose_1_1_invalid_map_name_exception.html", "d3/d9c/class_padamose_1_1_invalid_map_name_exception" ],
    [ "KeyNotFoundException", "d5/d87/class_padamose_1_1_key_not_found_exception.html", "d5/d87/class_padamose_1_1_key_not_found_exception" ],
    [ "OverwriteException", "d0/d81/class_padamose_1_1_overwrite_exception.html", "d0/d81/class_padamose_1_1_overwrite_exception" ],
    [ "TypeMismatchOnAssignException", "db/d6e/class_padamose_1_1_type_mismatch_on_assign_exception.html", "db/d6e/class_padamose_1_1_type_mismatch_on_assign_exception" ],
    [ "ValueStack", "dd/d4c/class_padamose_1_1_value_stack.html", "dd/d4c/class_padamose_1_1_value_stack" ],
    [ "VersionedBranch", "d4/da9/class_padamose_1_1_versioned_branch.html", "d4/da9/class_padamose_1_1_versioned_branch" ],
    [ "VersionedMap", "dd/dad/class_padamose_1_1_versioned_map.html", "dd/dad/class_padamose_1_1_versioned_map" ],
    [ "VersionedMapKeyCollisionException", "db/de5/class_padamose_1_1_versioned_map_key_collision_exception.html", "db/de5/class_padamose_1_1_versioned_map_key_collision_exception" ],
    [ "VersionedSet", "de/daa/class_padamose_1_1_versioned_set.html", "de/daa/class_padamose_1_1_versioned_set" ],
    [ "VersionedSetIterator", "de/d66/class_padamose_1_1_versioned_set_iterator.html", "de/d66/class_padamose_1_1_versioned_set_iterator" ],
    [ "VersionedSetNode", "dc/dea/class_padamose_1_1_versioned_set_node.html", "dc/dea/class_padamose_1_1_versioned_set_node" ],
    [ "VersionedSetNotFoundException", "d0/d60/class_padamose_1_1_versioned_set_not_found_exception.html", "d0/d60/class_padamose_1_1_versioned_set_not_found_exception" ],
    [ "VersionedSetSnapshot", "d6/db4/class_padamose_1_1_versioned_set_snapshot.html", "d6/db4/class_padamose_1_1_versioned_set_snapshot" ],
    [ "VersionedSetState", "dd/dc8/class_padamose_1_1_versioned_set_state.html", "dd/dc8/class_padamose_1_1_versioned_set_state" ],
    [ "VersionedStore", "d2/d73/class_padamose_1_1_versioned_store.html", "d2/d73/class_padamose_1_1_versioned_store" ],
    [ "VersionedStoreIterator", "d9/d05/class_padamose_1_1_versioned_store_iterator.html", "d9/d05/class_padamose_1_1_versioned_store_iterator" ],
    [ "VersionedStoreSnapshot", "d3/d20/class_padamose_1_1_versioned_store_snapshot.html", "d3/d20/class_padamose_1_1_versioned_store_snapshot" ],
    [ "VersionedValue", "df/d69/class_padamose_1_1_versioned_value.html", "df/d69/class_padamose_1_1_versioned_value" ],
    [ "VersionedValueIterator", "d8/ddf/class_padamose_1_1_versioned_value_iterator.html", "d8/ddf/class_padamose_1_1_versioned_value_iterator" ],
    [ "VersionOutOfBoundsException", "d1/dcb/class_padamose_1_1_version_out_of_bounds_exception.html", "d1/dcb/class_padamose_1_1_version_out_of_bounds_exception" ]
];