var namespace_padamose =
[
    [ "Test", "d3/dc0/namespace_padamose_1_1_test.html", "d3/dc0/namespace_padamose_1_1_test" ],
    [ "AbstractValueStack", "d2/d67/class_padamose_1_1_abstract_value_stack.html", "d2/d67/class_padamose_1_1_abstract_value_stack" ],
    [ "AbstractVersionedBranchClient", "d6/d41/class_padamose_1_1_abstract_versioned_branch_client.html", "d6/d41/class_padamose_1_1_abstract_versioned_branch_client" ],
    [ "AbstractVersionedCollection", "dc/dc4/class_padamose_1_1_abstract_versioned_collection.html", "dc/dc4/class_padamose_1_1_abstract_versioned_collection" ],
    [ "InvalidMapNameException", "d3/d9c/class_padamose_1_1_invalid_map_name_exception.html", "d3/d9c/class_padamose_1_1_invalid_map_name_exception" ],
    [ "KeyNotFoundException", "d5/d87/class_padamose_1_1_key_not_found_exception.html", "d5/d87/class_padamose_1_1_key_not_found_exception" ],
    [ "MutableVersionedCollection", "de/dfd/class_padamose_1_1_mutable_versioned_collection.html", "de/dfd/class_padamose_1_1_mutable_versioned_collection" ],
    [ "OverwriteException", "d0/d81/class_padamose_1_1_overwrite_exception.html", "d0/d81/class_padamose_1_1_overwrite_exception" ],
    [ "TypeMismatchOnAssignException", "db/d6e/class_padamose_1_1_type_mismatch_on_assign_exception.html", "db/d6e/class_padamose_1_1_type_mismatch_on_assign_exception" ],
    [ "ValueStack", "dd/d4c/class_padamose_1_1_value_stack.html", "dd/d4c/class_padamose_1_1_value_stack" ],
    [ "VersionedBranch", "d4/da9/class_padamose_1_1_versioned_branch.html", "d4/da9/class_padamose_1_1_versioned_branch" ],
    [ "VersionedCollectionIterator", "d7/de6/class_padamose_1_1_versioned_collection_iterator.html", "d7/de6/class_padamose_1_1_versioned_collection_iterator" ],
    [ "VersionedCollectionNode", "d0/d56/class_padamose_1_1_versioned_collection_node.html", "d0/d56/class_padamose_1_1_versioned_collection_node" ],
    [ "VersionedCollectionNotFoundException", "d5/d02/class_padamose_1_1_versioned_collection_not_found_exception.html", "d5/d02/class_padamose_1_1_versioned_collection_not_found_exception" ],
    [ "VersionedCollectionSnapshot", "d3/da8/class_padamose_1_1_versioned_collection_snapshot.html", "d3/da8/class_padamose_1_1_versioned_collection_snapshot" ],
    [ "VersionedCollectionState", "d9/dbb/class_padamose_1_1_versioned_collection_state.html", "d9/dbb/class_padamose_1_1_versioned_collection_state" ],
    [ "VersionedMap", "dd/dad/class_padamose_1_1_versioned_map.html", "dd/dad/class_padamose_1_1_versioned_map" ],
    [ "VersionedSet", "de/daa/class_padamose_1_1_versioned_set.html", "de/daa/class_padamose_1_1_versioned_set" ],
    [ "VersionedSetFreeStack", "d9/dd5/class_padamose_1_1_versioned_set_free_stack.html", "d9/dd5/class_padamose_1_1_versioned_set_free_stack" ],
    [ "VersionedStore", "d2/d73/class_padamose_1_1_versioned_store.html", "d2/d73/class_padamose_1_1_versioned_store" ],
    [ "VersionedStoreIterator", "d9/d05/class_padamose_1_1_versioned_store_iterator.html", "d9/d05/class_padamose_1_1_versioned_store_iterator" ],
    [ "VersionedStoreSnapshot", "d3/d20/class_padamose_1_1_versioned_store_snapshot.html", "d3/d20/class_padamose_1_1_versioned_store_snapshot" ],
    [ "VersionedValue", "df/d69/class_padamose_1_1_versioned_value.html", "df/d69/class_padamose_1_1_versioned_value" ],
    [ "VersionedValueIterator", "d8/ddf/class_padamose_1_1_versioned_value_iterator.html", "d8/ddf/class_padamose_1_1_versioned_value_iterator" ],
    [ "VersionOutOfBoundsException", "d1/dcb/class_padamose_1_1_version_out_of_bounds_exception.html", "d1/dcb/class_padamose_1_1_version_out_of_bounds_exception" ]
];